version: 2.1
jobs:
    run_tests:
        docker:
            -image: circleci/node@3.0.0

        steps:
            - checkout
            - run: 
                name: Install npm dependencies
                command: |
                    npm install --save
            - run:
                name: Run tests
                command: |
                    npm test


workflows:
  node-tests:
    jobs:
      - run_tests
