version: 2.1
jobs:
    run_tests:
        docker:
            - image: circleci/node:lts

        steps:
            - checkout
            - run: 
                name: Install npm dependencies
                command: |
                    npm install --save
            - run:
                name: Run tests
                command: |
                    npm test


workflows:
  node-tests:
    jobs:
      - run_tests
